name: Release APK

on:
  push:
    tags:
      - 'v*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Make Gradle executable
      run: chmod +x gradlew

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/debug/app-debug.apk
